all:
	gcc -w -Iinclude/ src/callbacks.c src/camera.c src/file.c src/init.c src/popupmenu.c src/main.c src/scene.c src/texture.c src/utils.c  -lwinmm -lSOIL -lobj -lopengl32 -lglu32 -lglut32 -lm -o solarsystem.exe
